apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  # Jira Configuration
  JIRA_INSTANCE: "{{ .Values.jira.instance }}"
  JIRA_USERNAME: "{{ .Values.jira.username }}"
  JIRA_API_TOKEN: "{{ .Values.jira.apiToken }}" # TODO: This should go in the external secret

  # OpenAI Configuration
  OPENAI_API_KEY: "{{ .Values.openai.apiKey }}" # TODO: This should go in the external secret
  OPENAI_API_VERSION: "{{ .Values.openai.apiVersion }}"
  OPENAI_TEMPERATURE: "{{ .Values.openai.temperature }}"

  # Azure OpenAI Configuration
  AZURE_OPENAI_API_KEY: "{{ .Values.azureOpenAI.apiKey }}"
  AZURE_OPENAI_ENDPOINT: "{{ .Values.azureOpenAI.endpoint }}"
  AZURE_OPENAI_DEPLOYMENT_NAME: "{{ .Values.azureOpenAI.deploymentName }}"
  AZURE_OPENAI_API_VERSION: "{{ .Values.azureOpenAI.apiVersion }}" # TODO: This should go in the external secret

  # LangChain Configuration
  LANGCHAIN_TRACING_V2: "{{ .Values.langchain.tracingV2 }}"
  LANGCHAIN_ENDPOINT: "{{ .Values.langchain.endpoint }}"
  LANGCHAIN_API_KEY: "{{ .Values.langchain.apiKey }}"
  LANGCHAIN_PROJECT: "{{ .Values.langchain.project }}"
  LANGSMITH_API_KEY: "{{ .Values.langsmith.apiKey }}" # TODO: This should go in the external secret