apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  # Jira Configuration
  JIRA_INSTANCE: "{{ .Values.jira.instance }}"
  JIRA_USERNAME: "{{ .Values.jira.username }}"
  LLM_PROVIDER: "{{ .Values.llmProvider }}"

  # OpenAI Configuration
  OPENAI_API_VERSION: "{{ .Values.openai.apiVersion }}"
  OPENAI_TEMPERATURE: "{{ .Values.openai.temperature }}"
  OPENAI_ENDPOINT: "{{ .Values.openai.endpoint }}"

  # Azure OpenAI Configuration
  AZURE_OPENAI_ENDPOINT: "{{ .Values.azureOpenAI.endpoint }}"
  AZURE_OPENAI_DEPLOYMENT_NAME: "{{ .Values.azureOpenAI.deploymentName }}"
  AZURE_OPENAI_API_VERSION: "{{ .Values.azureOpenAI.apiVersion }}"

  # LangChain Configuration
  LANGCHAIN_TRACING_V2: "{{ .Values.langchain.tracingV2 }}"
  LANGCHAIN_ENDPOINT: "{{ .Values.langchain.endpoint }}"
  LANGCHAIN_PROJECT: "{{ .Values.langchain.project }}"