GPT_DEPLOYMENT_NAME: # LLM GPT DEPLOYEMT NAME like gpt-4o
AZURE_OPENAI_API_KEY:  # LLM AZURE OPENAI API KEY
AZURE_OPENAI_ENDPOINT: # LLM AZURE OPENAI ENDPOINT
JIRA_SERVER:  # JIRA SERVER
JIRA_USER: # JIRA USER
JIRA_API_TOKEN:  # JIRA API TOKEN
KEY_GENERATION_FILE_PATH:  # The path to key generation file.
JIRA_ACTION_REPLAY_OUTPUT: # The path to the output of jira action replay file.