GPT_DEPLOYMENT_NAME: # eg: gpt-4o - LLM GPT DEPLOYEMT NAME like gpt-4o
AZURE_OPENAI_API_KEY:  # LLM AZURE OPENAI API KEY
AZURE_OPENAI_ENDPOINT:  # LLM AZURE OPENAI ENDPOINT
INITIAL_QUERIES_FILE: # eg: initial_queries.json - INITIAL QUERIES FILE
FINAL_OUTPUT_QUERIES_FILE:  # eg: key_generation.json - FINAL OUTPUT QUERIES FILE