GPT_DEPLOYMENT_NAME: # LLM GPT DEPLOYEMT NAME like gpt-4o
AZURE_OPENAI_API_KEY:  # LLM AZURE OPENAI API KEY
AZURE_OPENAI_ENDPOINT:  # LLM AZURE OPENAI ENDPOINT
INITIAL_QUERIES_FILE: # INITIAL QUERIES FILE
FINAL_OUTPUT_QUERIES_FILE:  # FINAL OUTPUT QUERIES FILE